sonar.projectKey=multiverse-project
sonar.projectName=Multiverse Microservices
sonar.projectVersion=1.0

# Archivos fuente
sonar.sources=frontend,pokemones,naruto/src,dragonball

# Exclusiones
sonar.exclusions=**/node_modules/**,**/target/**,**/*.json,**/*.xml

# Lenguajes
sonar.language=js,java,py,css,html
